// DESIGN.md §22 — Gates Config
export const gates = [
  {
    id:       'executive-blueprint',
    name:     'Executive Blueprint',
    label:    'Clarity before capital',
    bestFor:  'Founders who need clarity before capital.',
    color:    '--bs-silver',
    colorHex: '#c9c9c9',
    borderStyle: '1px solid rgba(201,201,201,0.42)',
    includes: [
      'Private vision extraction',
      'Custom business blueprint',
      'Clear income path',
      'Offer and brand direction',
      '30-day execution roadmap',
    ],
    cta: 'Start My Blueprint',
  },
  {
    id:       'silver-gate',
    name:     'Silver Gate',
    label:    'Ready to move now',
    bestFor:  'Builders ready to move now.',
    color:    '--bs-silver',
    colorHex: '#c9c9c9',
    borderStyle: '1px solid rgba(201,201,201,0.55)',
    includes: [
      'Executive Blueprint',
      'Corporate structure support',
      'EIN setup support',
      'Business credit / fundability preparation',
      'Member portal access',
      'Funding pathway positioning',
    ],
    cta: 'Enter Silver Gate',
  },
  {
    id:       'gold-gate',
    name:     'Gold Gate',
    label:    'Guidance and speed',
    bestFor:  'Builders who want guidance, speed, and deeper support.',
    color:    '--bs-gold',
    colorHex: '#c9a449',
    borderStyle: '1px solid rgba(201,164,73,0.55)',
    includes: [
      'Silver Gate',
      'Private strategic guidance',
      '12-month business credit consulting support',
      'High-level funding mentorship',
      'Accountability support',
      'Growth strategy',
    ],
    cta: 'Enter Gold Gate',
  },
  {
    id:       'platinum-gate',
    name:     'Platinum Gate',
    label:    'Premium execution',
    bestFor:  'Serious builders creating something significant.',
    color:    '--bs-gold-soft',
    colorHex: '#e0c878',
    borderStyle: '1px solid rgba(224,200,120,0.55)',
    includes: [
      'Gold Gate',
      'Website',
      'CRM + automation setup',
      'AI business systems',
      'Mobile app',
      'Ongoing technical support',
      'Premium execution support',
    ],
    cta: 'Enter Platinum Gate',
  },
  {
    id:       'scholarship',
    name:     'Black Sheep Blueprint Scholarship',
    label:    'Application required',
    bestFor:  'Ready applicants with financial barriers.',
    color:    '--bs-red',
    colorHex: '#b5121b',
    borderStyle: '1px solid rgba(181,18,27,0.35)',
    includes: [
      'Application review',
      'Story-based consideration',
      'Blueprint pathway opportunity',
      'Team approval required',
    ],
    cta: 'Apply for Scholarship',
  },
]
