// All 20+ tools — single source of truth for the web app
// Mirrors packages/shared/src/constants/tools.ts

export const ALL_TOOLS = [
  // ── Writing ──────────────────────────────────────────
  { id: 'email_writer',    name: 'Email Writer',    nameBn: 'ইমেইল লেখক',        icon: '📧', category: 'Writing',   description: 'Write professional emails for any situation',      descriptionBn: 'যেকোনো পরিস্থিতির জন্য পেশাদার ইমেইল লিখুন',  prompt: 'Write a professional email. Subject: {input}. Make it clear, polite, and effective.',                                                                          free: true  },
  { id: 'essay_writer',    name: 'Essay Writer',    nameBn: 'রচনা লেখক',          icon: '📄', category: 'Writing',   description: 'Write structured essays on any topic',             descriptionBn: 'যেকোনো বিষয়ে গঠনমূলক রচনা লিখুন',             prompt: 'Write a well-structured essay on: {input}. Include introduction, body paragraphs with evidence, and conclusion.',                                             free: true  },
  { id: 'blog_post',       name: 'Blog Post',       nameBn: 'ব্লগ পোস্ট',          icon: '📝', category: 'Writing',   description: 'Create engaging blog posts',                       descriptionBn: 'আকর্ষণীয় ব্লগ পোস্ট তৈরি করুন',                prompt: 'Write an engaging blog post about: {input}. Use a catchy headline, engaging intro, informative sections, and a call-to-action ending.',                        free: true  },
  { id: 'social_media',    name: 'Social Media Copy',nameBn:'সোশ্যাল মিডিয়া',    icon: '📱', category: 'Writing',   description: 'Write viral social media content',                 descriptionBn: 'ভাইরাল সোশ্যাল মিডিয়া কন্টেন্ট লিখুন',        prompt: 'Create engaging social media posts for: {input}. Include variations for Twitter/X, Facebook, Instagram, LinkedIn. Add relevant hashtags.',                   free: true  },
  { id: 'poetry',          name: 'Poetry',           nameBn: 'কবিতা',              icon: '🎭', category: 'Writing',   description: 'Write beautiful poems',                            descriptionBn: 'সুন্দর কবিতা লিখুন',                            prompt: 'Write a beautiful poem about: {input}. Be creative, use vivid imagery and emotional language.',                                                               free: true  },
  // ── Coding ───────────────────────────────────────────
  { id: 'python_code',     name: 'Python Code',     nameBn: 'পাইথন কোড',          icon: '🐍', category: 'Coding',    description: 'Write Python scripts and programs',               descriptionBn: 'পাইথন স্ক্রিপ্ট ও প্রোগ্রাম লিখুন',             prompt: 'Write clean, efficient Python code for: {input}. Include comments, error handling, and example usage.',                                                       free: true  },
  { id: 'web_dev',         name: 'Web Dev',          nameBn: 'ওয়েব ডেভ',           icon: '🌐', category: 'Coding',    description: 'Build websites with HTML, CSS & JS',              descriptionBn: 'HTML, CSS ও JS দিয়ে ওয়েবসাইট বানান',            prompt: 'Create a complete, responsive website for: {input}. Use modern HTML5, CSS3, and vanilla JavaScript. Make it visually appealing.',                             free: true  },
  { id: 'react_app',       name: 'React App',        nameBn: 'রিঅ্যাক্ট অ্যাপ',    icon: '⚛️', category: 'Coding',    description: 'Build React components and apps',                 descriptionBn: 'React কম্পোনেন্ট ও অ্যাপ তৈরি করুন',            prompt: 'Build a React component/app for: {input}. Use functional components, hooks, and TypeScript. Include proper props typing and state management.',               free: true  },
  { id: 'api_builder',     name: 'API Builder',      nameBn: 'API বিল্ডার',         icon: '⚡', category: 'Coding',    description: 'Design and implement REST APIs',                  descriptionBn: 'REST API ডিজাইন ও ইমপ্লিমেন্ট করুন',            prompt: 'Design and implement a REST API for: {input}. Include endpoint definitions, request/response schemas, authentication, and example Node.js/Express code.',     free: true  },
  // ── Education ────────────────────────────────────────
  { id: 'math_solver',     name: 'Math Solver',      nameBn: 'গণিত সমাধান',        icon: '🧮', category: 'Education', description: 'Solve math problems step by step',                descriptionBn: 'ধাপে ধাপে গণিত সমাধান করুন',                    prompt: 'Solve this math problem step by step: {input}. Show all working, explain each step clearly, and verify the answer.',                                          free: true  },
  { id: 'science_helper',  name: 'Science Helper',   nameBn: 'বিজ্ঞান সহায়ক',     icon: '⚗️', category: 'Education', description: 'Explain science concepts clearly',                descriptionBn: 'বিজ্ঞানের ধারণা স্পষ্টভাবে বুঝুন',              prompt: 'Explain this science concept clearly: {input}. Use simple language, real-world examples, and cover the key principles.',                                      free: true  },
  { id: 'history_expert',  name: 'History Expert',   nameBn: 'ইতিহাস বিশেষজ্ঞ',   icon: '📜', category: 'Education', description: 'Learn history with context and analysis',         descriptionBn: 'প্রসঙ্গ ও বিশ্লেষণ সহ ইতিহাস শিখুন',           prompt: 'Provide a detailed historical analysis of: {input}. Include timeline, key figures, causes, effects, and lasting significance.',                               free: true  },
  { id: 'language_tutor',  name: 'Language Tutor',   nameBn: 'ভাষা শিক্ষক',        icon: '🗣️', category: 'Education', description: 'Learn any language with expert guidance',         descriptionBn: 'বিশেষজ্ঞ নির্দেশনায় যেকোনো ভাষা শিখুন',        prompt: 'Teach me about this language/concept: {input}. Include vocabulary, grammar rules, example sentences, pronunciation tips, and practice exercises.',             free: true  },
  // ── Business ─────────────────────────────────────────
  { id: 'resume_builder',  name: 'Resume Builder',   nameBn: 'রেজিউমি বিল্ডার',    icon: '📋', category: 'Business',  description: 'Create professional resumes & CVs',               descriptionBn: 'পেশাদার রেজিউমি ও CV তৈরি করুন',                 prompt: 'Create a professional resume/CV for: {input}. Include objective statement, skills, experience formatting, education section, and ATS-friendly keywords.',      free: true  },
  { id: 'business_plan',   name: 'Business Plan',    nameBn: 'ব্যবসায়িক পরিকল্পনা',icon: '📈', category: 'Business',  description: 'Write comprehensive business plans',              descriptionBn: 'বিস্তারিত ব্যবসায়িক পরিকল্পনা লিখুন',          prompt: 'Write a comprehensive business plan for: {input}. Include executive summary, market analysis, competitive landscape, revenue model, and 12-month roadmap.',   free: true  },
  { id: 'marketing_copy',  name: 'Marketing Copy',   nameBn: 'মার্কেটিং কপি',      icon: '📣', category: 'Business',  description: 'Create compelling marketing materials',           descriptionBn: 'আকর্ষণীয় মার্কেটিং কন্টেন্ট তৈরি করুন',       prompt: 'Create compelling marketing copy for: {input}. Include tagline, value proposition, key benefits, social proof elements, and a strong call-to-action.',        free: true  },
  { id: 'pitch_deck',      name: 'Pitch Deck',       nameBn: 'পিচ ডেক',             icon: '🎯', category: 'Business',  description: 'Build investor-ready pitch decks',                descriptionBn: 'বিনিয়োগকারীদের জন্য পিচ ডেক তৈরি করুন',        prompt: 'Create an investor pitch deck outline for: {input}. Cover problem, solution, market size, business model, traction, team, and funding ask.',                 free: true  },
  // ── Creative ─────────────────────────────────────────
  { id: 'story_writer',    name: 'Story Writer',     nameBn: 'গল্প লেখক',           icon: '📖', category: 'Creative',  description: 'Write captivating stories',                       descriptionBn: 'মনোগ্রাহী গল্প লিখুন',                          prompt: 'Write a captivating short story about: {input}. Create compelling characters, vivid settings, conflict, and a satisfying resolution. Aim for 500-800 words.',  free: true  },
  { id: 'song_lyrics',     name: 'Song Lyrics',      nameBn: 'গানের কথা',           icon: '🎵', category: 'Creative',  description: 'Write song lyrics in any style',                  descriptionBn: 'যেকোনো স্টাইলে গানের কথা লিখুন',                prompt: 'Write song lyrics for: {input}. Include verses, chorus, bridge. Match the mood and style requested. Make the lyrics emotionally resonant and memorable.',      free: true  },
  { id: 'script_writer',   name: 'Script Writer',    nameBn: 'স্ক্রিপ্ট লেখক',      icon: '🎬', category: 'Creative',  description: 'Write scripts for video and theater',             descriptionBn: 'ভিডিও ও থিয়েটারের জন্য স্ক্রিপ্ট লিখুন',      prompt: 'Write a script for: {input}. Include scene descriptions, character dialogue, stage directions, and proper script formatting.',                                free: true  },
] as const

export type ToolCategory = 'Writing' | 'Coding' | 'Education' | 'Business' | 'Creative'

export const TOOL_CATEGORIES: ToolCategory[] = ['Writing', 'Coding', 'Education', 'Business', 'Creative']

export const CATEGORY_COLORS: Record<ToolCategory, string> = {
  Writing:   '#FFB628',
  Coding:    '#8B5CF6',
  Education: '#00E676',
  Business:  '#3B82F6',
  Creative:  '#EC4899',
}
